spring:
  application:
    name: product-manager
  datasource:
    url: jdbc:mariadb://localhost:3308/products-manager
    username: root
    password: admin123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  flyway:
    url: jdbc:mariadb://localhost:3308/products-manager
    schemas: products-manager
    user: root
    password: admin123