spring:
  application:
    name: product-manager
  datasource:
    url: jdbc:mariadb://localhost:3307/products-manager
    username: root
    password: admin123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
